version: '2'

services:
  db:
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  redis:
    restart: always
    image: redis:3
    ports:
      - "6379:6379"

  phpredmin:
    restart: always
    image: sasanrose/phpredmin
    environment:
        - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
        - "8090:80"
    depends_on:
        - redis

  nginx:
    restart: always
    image: nginx
    links:
      - kafka:kafka
      - rabbit1:rabbit1
      - zookeeper:zk
    depends_on:
      - kafka
      - rabbit1
      - zookeeper
    volumes:
      - "./.data/nginx/conf:/etc/nginx/conf.d"
    ports:
      - "80:80"

  rabbit1:
    restart: always
    image: bijukunjummen/rabbitmq-server
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
  
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    restart: always
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.33.10 
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    restart: always
    image: dockerkafka/kafka-manager
    depends_on:
      - zookeeper
      - kafka
    links:
      - zookeeper:zk
      - kafka:kafka
    environment:
      ZK_HOSTS: zk:2181
    ports:
      - "9000:9000"

  mongodb:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./.data/mongo/db:/data/db"
      - "./.data/mongo/configdb:/data/configdb"
