version: '2'

services:
  db:
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  redis:
    restart: always
    image: redis:3


  rabbit1:
    restart: always
    image: bijukunjummen/rabbitmq-server
    hostname: rabbit1
  
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
  
  kafka:
    restart: always
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  tomcat_socket:
    restart: always
    build: ./build/tomcat/
    volumes:
      - ./.data/liner/:/opt/xipinconf/zl/liner
      - ./.data/webapps/socket:/opt/tomcat/webapps
    depends_on:
      - redis
      - db
      - zookeeper
      - kafka
    links:
      - rabbit1:rabbit1
      - kafka:kafka

  tomcat_log:
    restart: always
    build: ./build/tomcat/
    volumes:
      - ./.data/liner/:/opt/xipinconf/zl/liner
      - ./.data/webapps/log:/opt/tomcat/webapps
    depends_on:
      - redis
      - db
      - zookeeper
      - kafka
      - tomcat_socket
    links:
      - rabbit1:rabbit1
      - kafka:kafka
      - tomcat_socket:tomcat_socket

  tomcat_fee:
    restart: always
    build: ./build/tomcat/
    volumes:
      - ./.data/liner/:/opt/xipinconf/zl/liner
      - ./.data/webapps/fee:/opt/tomcat/webapps
    depends_on:
      - redis
      - db
      - zookeeper
      - kafka
      - tomcat_socket
    links:
      - rabbit1:rabbit1
      - kafka:kafka
      - tomcat_socket:tomcat_socket

  tomcat_web:
    restart: always
    build: ./build/tomcat/
    volumes:
      - ./.data/liner/:/opt/xipinconf/zl/liner
      - ./.data/webapps/web:/opt/tomcat/webapps
    depends_on:
      - redis
      - db
      - zookeeper
      - kafka
      - tomcat_socket
      - tomcat_log
    links:
      - rabbit1:rabbit1
      - kafka:kafka
      - tomcat_socket:tomcat_socket
      - tomcat_log:tomcat_log
    ports:
      - 8080:8080
