version: '2'

services:
  db:
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  redis:
    restart: always
    image: redis:3
    ports:
      - "6379:6379"

  nginx:
    restart: always
    image: bitnami/nginx
    volumes:
      - "./.data/nginx/config:/bitnami/nginx/conf"
      - "./.data/nginx/www:/opt/bitnami/nginx/html"
    ports:
      - "80:80"

  rabbit1:
    image: bijukunjummen/rabbitmq-server
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"

